name: Python App CI/CD Pipeline with Direct Deploymentt

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'  

    # Install dependencies
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # Run tests
    - name: Run tests
      run: |
        echo "Run tests"

    # Login to Azure
    - name: Azure Login
      uses: azure/login@v2.2.0
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    

    # Update the VM with secure token passing
    - name: Azure VMSS Update
      run: |
       az vmss extension set \
        --resource-group ${{ secrets.RESOURCE_GROUP }} \
        --vmss-name ${{ secrets.VM_NAME }} \
        --name CustomScript \
        --force-update \
        --publisher Microsoft.Azure.Extensions \
        --type-handler-version 2.1 \
        --settings '{"fileUris": []}' \
        --protected-settings @.github/azure-settings.json
